//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchivoWebService.ServicioArchivo {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Services/")]
    public partial class IOException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Services/", ConfigurationName="ServicioArchivo.ServicioDeArchivo")]
    public interface ServicioDeArchivo {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services/ServicioDeArchivo/helloRequest", ReplyAction="http://Services/ServicioDeArchivo/helloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ArchivoWebService.ServicioArchivo.helloResponse hello(ArchivoWebService.ServicioArchivo.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services/ServicioDeArchivo/helloRequest", ReplyAction="http://Services/ServicioDeArchivo/helloResponse")]
        System.Threading.Tasks.Task<ArchivoWebService.ServicioArchivo.helloResponse> helloAsync(ArchivoWebService.ServicioArchivo.helloRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services/ServicioDeArchivo/descifrarRequest", ReplyAction="http://Services/ServicioDeArchivo/descifrarResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ArchivoWebService.ServicioArchivo.IOException), Action="http://Services/ServicioDeArchivo/descifrar/Fault/IOException", Name="IOException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ArchivoWebService.ServicioArchivo.descifrarResponse descifrar(ArchivoWebService.ServicioArchivo.descifrarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services/ServicioDeArchivo/descifrarRequest", ReplyAction="http://Services/ServicioDeArchivo/descifrarResponse")]
        System.Threading.Tasks.Task<ArchivoWebService.ServicioArchivo.descifrarResponse> descifrarAsync(ArchivoWebService.ServicioArchivo.descifrarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services/ServicioDeArchivo/cifrarRequest", ReplyAction="http://Services/ServicioDeArchivo/cifrarResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ArchivoWebService.ServicioArchivo.IOException), Action="http://Services/ServicioDeArchivo/cifrar/Fault/IOException", Name="IOException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ArchivoWebService.ServicioArchivo.cifrarResponse cifrar(ArchivoWebService.ServicioArchivo.cifrarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services/ServicioDeArchivo/cifrarRequest", ReplyAction="http://Services/ServicioDeArchivo/cifrarResponse")]
        System.Threading.Tasks.Task<ArchivoWebService.ServicioArchivo.cifrarResponse> cifrarAsync(ArchivoWebService.ServicioArchivo.cifrarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hello", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        public helloRequest() {
        }
        
        public helloRequest(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="helloResponse", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public helloResponse() {
        }
        
        public helloResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="descifrar", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class descifrarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] arg0;
        
        public descifrarRequest() {
        }
        
        public descifrarRequest(byte[] arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="descifrarResponse", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class descifrarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] @return;
        
        public descifrarResponse() {
        }
        
        public descifrarResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cifrar", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class cifrarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] arg0;
        
        public cifrarRequest() {
        }
        
        public cifrarRequest(byte[] arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cifrarResponse", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class cifrarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] @return;
        
        public cifrarResponse() {
        }
        
        public cifrarResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioDeArchivoChannel : ArchivoWebService.ServicioArchivo.ServicioDeArchivo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioDeArchivoClient : System.ServiceModel.ClientBase<ArchivoWebService.ServicioArchivo.ServicioDeArchivo>, ArchivoWebService.ServicioArchivo.ServicioDeArchivo {
        
        public ServicioDeArchivoClient() {
        }
        
        public ServicioDeArchivoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioDeArchivoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioDeArchivoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioDeArchivoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ArchivoWebService.ServicioArchivo.helloResponse ArchivoWebService.ServicioArchivo.ServicioDeArchivo.hello(ArchivoWebService.ServicioArchivo.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            ArchivoWebService.ServicioArchivo.helloRequest inValue = new ArchivoWebService.ServicioArchivo.helloRequest();
            inValue.name = name;
            ArchivoWebService.ServicioArchivo.helloResponse retVal = ((ArchivoWebService.ServicioArchivo.ServicioDeArchivo)(this)).hello(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ArchivoWebService.ServicioArchivo.helloResponse> ArchivoWebService.ServicioArchivo.ServicioDeArchivo.helloAsync(ArchivoWebService.ServicioArchivo.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<ArchivoWebService.ServicioArchivo.helloResponse> helloAsync(string name) {
            ArchivoWebService.ServicioArchivo.helloRequest inValue = new ArchivoWebService.ServicioArchivo.helloRequest();
            inValue.name = name;
            return ((ArchivoWebService.ServicioArchivo.ServicioDeArchivo)(this)).helloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ArchivoWebService.ServicioArchivo.descifrarResponse ArchivoWebService.ServicioArchivo.ServicioDeArchivo.descifrar(ArchivoWebService.ServicioArchivo.descifrarRequest request) {
            return base.Channel.descifrar(request);
        }
        
        public byte[] descifrar(byte[] arg0) {
            ArchivoWebService.ServicioArchivo.descifrarRequest inValue = new ArchivoWebService.ServicioArchivo.descifrarRequest();
            inValue.arg0 = arg0;
            ArchivoWebService.ServicioArchivo.descifrarResponse retVal = ((ArchivoWebService.ServicioArchivo.ServicioDeArchivo)(this)).descifrar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ArchivoWebService.ServicioArchivo.descifrarResponse> ArchivoWebService.ServicioArchivo.ServicioDeArchivo.descifrarAsync(ArchivoWebService.ServicioArchivo.descifrarRequest request) {
            return base.Channel.descifrarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ArchivoWebService.ServicioArchivo.descifrarResponse> descifrarAsync(byte[] arg0) {
            ArchivoWebService.ServicioArchivo.descifrarRequest inValue = new ArchivoWebService.ServicioArchivo.descifrarRequest();
            inValue.arg0 = arg0;
            return ((ArchivoWebService.ServicioArchivo.ServicioDeArchivo)(this)).descifrarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ArchivoWebService.ServicioArchivo.cifrarResponse ArchivoWebService.ServicioArchivo.ServicioDeArchivo.cifrar(ArchivoWebService.ServicioArchivo.cifrarRequest request) {
            return base.Channel.cifrar(request);
        }
        
        public byte[] cifrar(byte[] arg0) {
            ArchivoWebService.ServicioArchivo.cifrarRequest inValue = new ArchivoWebService.ServicioArchivo.cifrarRequest();
            inValue.arg0 = arg0;
            ArchivoWebService.ServicioArchivo.cifrarResponse retVal = ((ArchivoWebService.ServicioArchivo.ServicioDeArchivo)(this)).cifrar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ArchivoWebService.ServicioArchivo.cifrarResponse> ArchivoWebService.ServicioArchivo.ServicioDeArchivo.cifrarAsync(ArchivoWebService.ServicioArchivo.cifrarRequest request) {
            return base.Channel.cifrarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ArchivoWebService.ServicioArchivo.cifrarResponse> cifrarAsync(byte[] arg0) {
            ArchivoWebService.ServicioArchivo.cifrarRequest inValue = new ArchivoWebService.ServicioArchivo.cifrarRequest();
            inValue.arg0 = arg0;
            return ((ArchivoWebService.ServicioArchivo.ServicioDeArchivo)(this)).cifrarAsync(inValue);
        }
    }
}
