//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchivoWebService.ServicioArchivo {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Services/")]
    public partial class IOException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Services/", ConfigurationName="ServicioArchivo.ServicioDeArchivo")]
    public interface ServicioDeArchivo {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services/ServicioDeArchivo/createFileRequest", ReplyAction="http://Services/ServicioDeArchivo/createFileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ArchivoWebService.ServicioArchivo.IOException), Action="http://Services/ServicioDeArchivo/createFile/Fault/IOException", Name="IOException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ArchivoWebService.ServicioArchivo.createFileResponse createFile(ArchivoWebService.ServicioArchivo.createFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services/ServicioDeArchivo/createFileRequest", ReplyAction="http://Services/ServicioDeArchivo/createFileResponse")]
        System.Threading.Tasks.Task<ArchivoWebService.ServicioArchivo.createFileResponse> createFileAsync(ArchivoWebService.ServicioArchivo.createFileRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services/ServicioDeArchivo/getNumberOfChunksRequest", ReplyAction="http://Services/ServicioDeArchivo/getNumberOfChunksResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ArchivoWebService.ServicioArchivo.IOException), Action="http://Services/ServicioDeArchivo/getNumberOfChunks/Fault/IOException", Name="IOException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ArchivoWebService.ServicioArchivo.getNumberOfChunksResponse getNumberOfChunks(ArchivoWebService.ServicioArchivo.getNumberOfChunksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services/ServicioDeArchivo/getNumberOfChunksRequest", ReplyAction="http://Services/ServicioDeArchivo/getNumberOfChunksResponse")]
        System.Threading.Tasks.Task<ArchivoWebService.ServicioArchivo.getNumberOfChunksResponse> getNumberOfChunksAsync(ArchivoWebService.ServicioArchivo.getNumberOfChunksRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services/ServicioDeArchivo/getNChunkRequest", ReplyAction="http://Services/ServicioDeArchivo/getNChunkResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ArchivoWebService.ServicioArchivo.IOException), Action="http://Services/ServicioDeArchivo/getNChunk/Fault/IOException", Name="IOException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ArchivoWebService.ServicioArchivo.getNChunkResponse getNChunk(ArchivoWebService.ServicioArchivo.getNChunkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services/ServicioDeArchivo/getNChunkRequest", ReplyAction="http://Services/ServicioDeArchivo/getNChunkResponse")]
        System.Threading.Tasks.Task<ArchivoWebService.ServicioArchivo.getNChunkResponse> getNChunkAsync(ArchivoWebService.ServicioArchivo.getNChunkRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services/ServicioDeArchivo/getFileAsJFileRequest", ReplyAction="http://Services/ServicioDeArchivo/getFileAsJFileResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ArchivoWebService.ServicioArchivo.getFileAsJFileResponse getFileAsJFile(ArchivoWebService.ServicioArchivo.getFileAsJFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services/ServicioDeArchivo/getFileAsJFileRequest", ReplyAction="http://Services/ServicioDeArchivo/getFileAsJFileResponse")]
        System.Threading.Tasks.Task<ArchivoWebService.ServicioArchivo.getFileAsJFileResponse> getFileAsJFileAsync(ArchivoWebService.ServicioArchivo.getFileAsJFileRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services/ServicioDeArchivo/helloRequest", ReplyAction="http://Services/ServicioDeArchivo/helloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ArchivoWebService.ServicioArchivo.helloResponse hello(ArchivoWebService.ServicioArchivo.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services/ServicioDeArchivo/helloRequest", ReplyAction="http://Services/ServicioDeArchivo/helloResponse")]
        System.Threading.Tasks.Task<ArchivoWebService.ServicioArchivo.helloResponse> helloAsync(ArchivoWebService.ServicioArchivo.helloRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services/ServicioDeArchivo/sendBytesRequest", ReplyAction="http://Services/ServicioDeArchivo/sendBytesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ArchivoWebService.ServicioArchivo.IOException), Action="http://Services/ServicioDeArchivo/sendBytes/Fault/IOException", Name="IOException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ArchivoWebService.ServicioArchivo.sendBytesResponse sendBytes(ArchivoWebService.ServicioArchivo.sendBytesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services/ServicioDeArchivo/sendBytesRequest", ReplyAction="http://Services/ServicioDeArchivo/sendBytesResponse")]
        System.Threading.Tasks.Task<ArchivoWebService.ServicioArchivo.sendBytesResponse> sendBytesAsync(ArchivoWebService.ServicioArchivo.sendBytesRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services/ServicioDeArchivo/getFileAsBytesRequest", ReplyAction="http://Services/ServicioDeArchivo/getFileAsBytesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ArchivoWebService.ServicioArchivo.IOException), Action="http://Services/ServicioDeArchivo/getFileAsBytes/Fault/IOException", Name="IOException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ArchivoWebService.ServicioArchivo.getFileAsBytesResponse getFileAsBytes(ArchivoWebService.ServicioArchivo.getFileAsBytesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services/ServicioDeArchivo/getFileAsBytesRequest", ReplyAction="http://Services/ServicioDeArchivo/getFileAsBytesResponse")]
        System.Threading.Tasks.Task<ArchivoWebService.ServicioArchivo.getFileAsBytesResponse> getFileAsBytesAsync(ArchivoWebService.ServicioArchivo.getFileAsBytesRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services/ServicioDeArchivo/getNameOfFileRequest", ReplyAction="http://Services/ServicioDeArchivo/getNameOfFileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ArchivoWebService.ServicioArchivo.IOException), Action="http://Services/ServicioDeArchivo/getNameOfFile/Fault/IOException", Name="IOException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ArchivoWebService.ServicioArchivo.getNameOfFileResponse getNameOfFile(ArchivoWebService.ServicioArchivo.getNameOfFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services/ServicioDeArchivo/getNameOfFileRequest", ReplyAction="http://Services/ServicioDeArchivo/getNameOfFileResponse")]
        System.Threading.Tasks.Task<ArchivoWebService.ServicioArchivo.getNameOfFileResponse> getNameOfFileAsync(ArchivoWebService.ServicioArchivo.getNameOfFileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createFile", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class createFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public createFileRequest() {
        }
        
        public createFileRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createFileResponse", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class createFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public createFileResponse() {
        }
        
        public createFileResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getNumberOfChunks", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class getNumberOfChunksRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getNumberOfChunksRequest() {
        }
        
        public getNumberOfChunksRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getNumberOfChunksResponse", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class getNumberOfChunksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public getNumberOfChunksResponse() {
        }
        
        public getNumberOfChunksResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getNChunk", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class getNChunkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg1;
        
        public getNChunkRequest() {
        }
        
        public getNChunkRequest(string arg0, long arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getNChunkResponse", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class getNChunkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] @return;
        
        public getNChunkResponse() {
        }
        
        public getNChunkResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFileAsJFile", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class getFileAsJFileRequest {
        
        public getFileAsJFileRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFileAsJFileResponse", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class getFileAsJFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getFileAsJFileResponse() {
        }
        
        public getFileAsJFileResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hello", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        public helloRequest() {
        }
        
        public helloRequest(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="helloResponse", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public helloResponse() {
        }
        
        public helloResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendBytes", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class sendBytesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public sendBytesRequest() {
        }
        
        public sendBytesRequest(byte[] arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendBytesResponse", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class sendBytesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public sendBytesResponse() {
        }
        
        public sendBytesResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFileAsBytes", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class getFileAsBytesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getFileAsBytesRequest() {
        }
        
        public getFileAsBytesRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFileAsBytesResponse", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class getFileAsBytesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] @return;
        
        public getFileAsBytesResponse() {
        }
        
        public getFileAsBytesResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getNameOfFile", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class getNameOfFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getNameOfFileRequest() {
        }
        
        public getNameOfFileRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getNameOfFileResponse", WrapperNamespace="http://Services/", IsWrapped=true)]
    public partial class getNameOfFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getNameOfFileResponse() {
        }
        
        public getNameOfFileResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioDeArchivoChannel : ArchivoWebService.ServicioArchivo.ServicioDeArchivo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioDeArchivoClient : System.ServiceModel.ClientBase<ArchivoWebService.ServicioArchivo.ServicioDeArchivo>, ArchivoWebService.ServicioArchivo.ServicioDeArchivo {
        
        public ServicioDeArchivoClient() {
        }
        
        public ServicioDeArchivoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioDeArchivoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioDeArchivoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioDeArchivoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ArchivoWebService.ServicioArchivo.createFileResponse ArchivoWebService.ServicioArchivo.ServicioDeArchivo.createFile(ArchivoWebService.ServicioArchivo.createFileRequest request) {
            return base.Channel.createFile(request);
        }
        
        public int createFile(string arg0) {
            ArchivoWebService.ServicioArchivo.createFileRequest inValue = new ArchivoWebService.ServicioArchivo.createFileRequest();
            inValue.arg0 = arg0;
            ArchivoWebService.ServicioArchivo.createFileResponse retVal = ((ArchivoWebService.ServicioArchivo.ServicioDeArchivo)(this)).createFile(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ArchivoWebService.ServicioArchivo.createFileResponse> ArchivoWebService.ServicioArchivo.ServicioDeArchivo.createFileAsync(ArchivoWebService.ServicioArchivo.createFileRequest request) {
            return base.Channel.createFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<ArchivoWebService.ServicioArchivo.createFileResponse> createFileAsync(string arg0) {
            ArchivoWebService.ServicioArchivo.createFileRequest inValue = new ArchivoWebService.ServicioArchivo.createFileRequest();
            inValue.arg0 = arg0;
            return ((ArchivoWebService.ServicioArchivo.ServicioDeArchivo)(this)).createFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ArchivoWebService.ServicioArchivo.getNumberOfChunksResponse ArchivoWebService.ServicioArchivo.ServicioDeArchivo.getNumberOfChunks(ArchivoWebService.ServicioArchivo.getNumberOfChunksRequest request) {
            return base.Channel.getNumberOfChunks(request);
        }
        
        public int getNumberOfChunks(string arg0) {
            ArchivoWebService.ServicioArchivo.getNumberOfChunksRequest inValue = new ArchivoWebService.ServicioArchivo.getNumberOfChunksRequest();
            inValue.arg0 = arg0;
            ArchivoWebService.ServicioArchivo.getNumberOfChunksResponse retVal = ((ArchivoWebService.ServicioArchivo.ServicioDeArchivo)(this)).getNumberOfChunks(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ArchivoWebService.ServicioArchivo.getNumberOfChunksResponse> ArchivoWebService.ServicioArchivo.ServicioDeArchivo.getNumberOfChunksAsync(ArchivoWebService.ServicioArchivo.getNumberOfChunksRequest request) {
            return base.Channel.getNumberOfChunksAsync(request);
        }
        
        public System.Threading.Tasks.Task<ArchivoWebService.ServicioArchivo.getNumberOfChunksResponse> getNumberOfChunksAsync(string arg0) {
            ArchivoWebService.ServicioArchivo.getNumberOfChunksRequest inValue = new ArchivoWebService.ServicioArchivo.getNumberOfChunksRequest();
            inValue.arg0 = arg0;
            return ((ArchivoWebService.ServicioArchivo.ServicioDeArchivo)(this)).getNumberOfChunksAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ArchivoWebService.ServicioArchivo.getNChunkResponse ArchivoWebService.ServicioArchivo.ServicioDeArchivo.getNChunk(ArchivoWebService.ServicioArchivo.getNChunkRequest request) {
            return base.Channel.getNChunk(request);
        }
        
        public byte[] getNChunk(string arg0, long arg1) {
            ArchivoWebService.ServicioArchivo.getNChunkRequest inValue = new ArchivoWebService.ServicioArchivo.getNChunkRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            ArchivoWebService.ServicioArchivo.getNChunkResponse retVal = ((ArchivoWebService.ServicioArchivo.ServicioDeArchivo)(this)).getNChunk(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ArchivoWebService.ServicioArchivo.getNChunkResponse> ArchivoWebService.ServicioArchivo.ServicioDeArchivo.getNChunkAsync(ArchivoWebService.ServicioArchivo.getNChunkRequest request) {
            return base.Channel.getNChunkAsync(request);
        }
        
        public System.Threading.Tasks.Task<ArchivoWebService.ServicioArchivo.getNChunkResponse> getNChunkAsync(string arg0, long arg1) {
            ArchivoWebService.ServicioArchivo.getNChunkRequest inValue = new ArchivoWebService.ServicioArchivo.getNChunkRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((ArchivoWebService.ServicioArchivo.ServicioDeArchivo)(this)).getNChunkAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ArchivoWebService.ServicioArchivo.getFileAsJFileResponse ArchivoWebService.ServicioArchivo.ServicioDeArchivo.getFileAsJFile(ArchivoWebService.ServicioArchivo.getFileAsJFileRequest request) {
            return base.Channel.getFileAsJFile(request);
        }
        
        public string getFileAsJFile() {
            ArchivoWebService.ServicioArchivo.getFileAsJFileRequest inValue = new ArchivoWebService.ServicioArchivo.getFileAsJFileRequest();
            ArchivoWebService.ServicioArchivo.getFileAsJFileResponse retVal = ((ArchivoWebService.ServicioArchivo.ServicioDeArchivo)(this)).getFileAsJFile(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ArchivoWebService.ServicioArchivo.getFileAsJFileResponse> ArchivoWebService.ServicioArchivo.ServicioDeArchivo.getFileAsJFileAsync(ArchivoWebService.ServicioArchivo.getFileAsJFileRequest request) {
            return base.Channel.getFileAsJFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<ArchivoWebService.ServicioArchivo.getFileAsJFileResponse> getFileAsJFileAsync() {
            ArchivoWebService.ServicioArchivo.getFileAsJFileRequest inValue = new ArchivoWebService.ServicioArchivo.getFileAsJFileRequest();
            return ((ArchivoWebService.ServicioArchivo.ServicioDeArchivo)(this)).getFileAsJFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ArchivoWebService.ServicioArchivo.helloResponse ArchivoWebService.ServicioArchivo.ServicioDeArchivo.hello(ArchivoWebService.ServicioArchivo.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            ArchivoWebService.ServicioArchivo.helloRequest inValue = new ArchivoWebService.ServicioArchivo.helloRequest();
            inValue.name = name;
            ArchivoWebService.ServicioArchivo.helloResponse retVal = ((ArchivoWebService.ServicioArchivo.ServicioDeArchivo)(this)).hello(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ArchivoWebService.ServicioArchivo.helloResponse> ArchivoWebService.ServicioArchivo.ServicioDeArchivo.helloAsync(ArchivoWebService.ServicioArchivo.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<ArchivoWebService.ServicioArchivo.helloResponse> helloAsync(string name) {
            ArchivoWebService.ServicioArchivo.helloRequest inValue = new ArchivoWebService.ServicioArchivo.helloRequest();
            inValue.name = name;
            return ((ArchivoWebService.ServicioArchivo.ServicioDeArchivo)(this)).helloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ArchivoWebService.ServicioArchivo.sendBytesResponse ArchivoWebService.ServicioArchivo.ServicioDeArchivo.sendBytes(ArchivoWebService.ServicioArchivo.sendBytesRequest request) {
            return base.Channel.sendBytes(request);
        }
        
        public int sendBytes(byte[] arg0, string arg1) {
            ArchivoWebService.ServicioArchivo.sendBytesRequest inValue = new ArchivoWebService.ServicioArchivo.sendBytesRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            ArchivoWebService.ServicioArchivo.sendBytesResponse retVal = ((ArchivoWebService.ServicioArchivo.ServicioDeArchivo)(this)).sendBytes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ArchivoWebService.ServicioArchivo.sendBytesResponse> ArchivoWebService.ServicioArchivo.ServicioDeArchivo.sendBytesAsync(ArchivoWebService.ServicioArchivo.sendBytesRequest request) {
            return base.Channel.sendBytesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ArchivoWebService.ServicioArchivo.sendBytesResponse> sendBytesAsync(byte[] arg0, string arg1) {
            ArchivoWebService.ServicioArchivo.sendBytesRequest inValue = new ArchivoWebService.ServicioArchivo.sendBytesRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((ArchivoWebService.ServicioArchivo.ServicioDeArchivo)(this)).sendBytesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ArchivoWebService.ServicioArchivo.getFileAsBytesResponse ArchivoWebService.ServicioArchivo.ServicioDeArchivo.getFileAsBytes(ArchivoWebService.ServicioArchivo.getFileAsBytesRequest request) {
            return base.Channel.getFileAsBytes(request);
        }
        
        public byte[] getFileAsBytes(string arg0) {
            ArchivoWebService.ServicioArchivo.getFileAsBytesRequest inValue = new ArchivoWebService.ServicioArchivo.getFileAsBytesRequest();
            inValue.arg0 = arg0;
            ArchivoWebService.ServicioArchivo.getFileAsBytesResponse retVal = ((ArchivoWebService.ServicioArchivo.ServicioDeArchivo)(this)).getFileAsBytes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ArchivoWebService.ServicioArchivo.getFileAsBytesResponse> ArchivoWebService.ServicioArchivo.ServicioDeArchivo.getFileAsBytesAsync(ArchivoWebService.ServicioArchivo.getFileAsBytesRequest request) {
            return base.Channel.getFileAsBytesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ArchivoWebService.ServicioArchivo.getFileAsBytesResponse> getFileAsBytesAsync(string arg0) {
            ArchivoWebService.ServicioArchivo.getFileAsBytesRequest inValue = new ArchivoWebService.ServicioArchivo.getFileAsBytesRequest();
            inValue.arg0 = arg0;
            return ((ArchivoWebService.ServicioArchivo.ServicioDeArchivo)(this)).getFileAsBytesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ArchivoWebService.ServicioArchivo.getNameOfFileResponse ArchivoWebService.ServicioArchivo.ServicioDeArchivo.getNameOfFile(ArchivoWebService.ServicioArchivo.getNameOfFileRequest request) {
            return base.Channel.getNameOfFile(request);
        }
        
        public string getNameOfFile(string arg0) {
            ArchivoWebService.ServicioArchivo.getNameOfFileRequest inValue = new ArchivoWebService.ServicioArchivo.getNameOfFileRequest();
            inValue.arg0 = arg0;
            ArchivoWebService.ServicioArchivo.getNameOfFileResponse retVal = ((ArchivoWebService.ServicioArchivo.ServicioDeArchivo)(this)).getNameOfFile(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ArchivoWebService.ServicioArchivo.getNameOfFileResponse> ArchivoWebService.ServicioArchivo.ServicioDeArchivo.getNameOfFileAsync(ArchivoWebService.ServicioArchivo.getNameOfFileRequest request) {
            return base.Channel.getNameOfFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<ArchivoWebService.ServicioArchivo.getNameOfFileResponse> getNameOfFileAsync(string arg0) {
            ArchivoWebService.ServicioArchivo.getNameOfFileRequest inValue = new ArchivoWebService.ServicioArchivo.getNameOfFileRequest();
            inValue.arg0 = arg0;
            return ((ArchivoWebService.ServicioArchivo.ServicioDeArchivo)(this)).getNameOfFileAsync(inValue);
        }
    }
}
